<h1 class="mb-5">Adicionar campanha</h1>

<form
	method="post"
	enctype="multipart/form-data">
	<div class="card-body">
		<div class="mb-3">
			<label
				for="nameInput"
				class="form-label"
				>Nome</label
			>
			<input
				type="text"
				class="form-control"
				id="nameInput"
				name="name"
				required
				autofocus
				value="<?= isset($sale) ? $sale->name : '' ?>" />
		</div>
		<div class="mb-3">
			<label
				for="descriptionInput"
				class="form-label"
				>Descrição</label
			>
			<textarea
				class="form-control"
				rows="4"
				id="descriptionInput"
				name="description"
				required
				><?= isset($sale) ? $sale->description : '' ?></textarea>
		</div>
		<div class="mb-3">
			<label
				for="startDate"
				class="form-label"
				>Inicia a</label
			>
			<input
				type="date"
				class="form-control"
				id="startDate"
				name="startDate"
				value="<?= isset($sale) ? $sale->startDate : '' ?>" />
		</div>
		<div class="mb-3">
			<label
				for="endDate"
				class="form-label"
				>Termina a</label
			>
			<input
				type="date"
				class="form-control"
				id="endDate"
				name="endDate"
				value="<?= isset($sale) ? $sale->endDate : '' ?>" />
		</div>

		<div class="mb-3">
			<label
				for="imageInput"
				class="form-label"
				>Imagem</label
			>
			<input
				type="file"
				name="image"
				id="imageInput"
				class="form-control" />
		</div>

		<?php if (isset($sale) && isset($sale->image)) : ?>
		<img
			src="/<?= $sale->image ?>"
			class="img-thumbnail mt-2"
			width="200" />
		<?php endif; ?>
	</div>

	<div class="card-footer d-flex justify-content-end">
		<button
			type="submit"
			class="btn btn-primary mb-5">
			Guardar
		</button>
	</div>
</form>
