<form class="d-flex mb-4" action="/sales/list" method="get">
	<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search" value="<?= isset($_GET['search']) ? $_GET['search'] : '' ?>">
	<button class="btn btn-outline-primary" type="submit">Search</button>
</form>

<div class="d-flex flex-row flex-wrap mb-4 ">
	<?php if (count($sales) >
	0) : foreach ($sales as $sale) : ?>

	<?php render('sales/card', ['sale' =>
	$sale], false); ?>

	<?php endforeach; else : ?>

	<p>Não há campanhas criadas.</p>

	<?php endif; ?>
</div>

<a
	href="/sales/create"
	class="btn btn-primary mb-5 btn-lg w-100"
	>Adicionar campanha</a
>
